CREATE TABLE users (
    user_id VARCHAR(255) PRIMARY KEY,
    full_name VARCHAR(255),
    profile_picture VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);